### ISSUE TITLE
Console warning docs links are broken

### ISSUE THREAD

**Issue by brylok** [pykih/PykCharts.js#11]
The warning links given in the console point to docs pages that do not exist. 

Example: [Warning - Pykih Charts]   at #some_graph.("You seem to have passed Date data so please pass the value for axis_x_time_value_datatype")  Visit www.chartstore.io/docs#warning_15

**Comment by ronakrrb** [comment]
We are working on it. Thanks for notifying

**Comment by ronakrrb** [comment]
The errors and warning links are updated in the console and hence closing this issue
