### ISSUE TITLE
Dependancies

### ISSUE THREAD

**Issue by nblackburn** [pykih/PykCharts.js#12]
As awesome as this looks, it seems to have an insane amount of dependencies which makes me uneasy. I understand D3 is needed and can warrant it's size because of how powerful it is.

However you also have Jquery and Bootstrap  and some other dependencies (some even relying on others) which themselves are monolithic, bloated beasts that are hugely abused for little to no reason. 

Ultimately these dependencies are not needed nor worth the cost they come at as they are **NEVER** fully utilized.

**Comment by ronakrrb** [comment]
Thanks for the feedback. Jquery and Bootstrap are not being used in the distribution file. The dependent files are only those which are in pykih-charts/assets/lib

**Comment by nblackburn** [comment]
Thanks and sorry for carelessly freaking out at the sight of the **lib** directory in this repo.
