### ISSUE TITLE
Not able to open data file in Windows computer

### ISSUE THREAD

**Issue by MoellerR** [pykih/PykCharts.js#14]
I tried to test PykCharts.js on my Windows computer by downloading the data file used in the example "line.html" from:

https://s3-ap-southeast-1.amazonaws.com/chartstore.io-data/line.csv

I changed then the corresponding code in "line.html" to:

"data": "../line.csv"

After the change above, the chart is not being generated anymore.

**Comment by ronakrrb** [comment]
Hello MoellerR,

You may be getting an error in the console:
    `Failed to load resource: the server responded with a status of 403 (Forbidden)`
Can you please give the access rights to the file? You can check http://answers.microsoft.com/en-us/windows/forum/windows_vista-files/how-do-i-change-folder-and-file-permissions/465f2b42-63dd-4486-8dd1-c870290efeed?auth=1 for the steps.

Thanks for using PykCharts.js
