### ISSUE TITLE
Not working with google spreadsheets publish csv

### ISSUE THREAD

**Issue by answerquest** [pykih/PykCharts.js#16]
Hi, thanks for making such a wonderful solution. I want to use a regularly updating google spreadsheet as the data source. I tried many different ways.. with other services at least using the `http://cors.io/?u=` prefix does the trick, but here I'm only getting a contonuous loading sign, and the page seems to be stuck in an infinite loop. The scrollbars indicate the page is becoming filled with a lot of stuff (invisible), and then in half a second it resets to no scrollbars, and then repeat.

For you reference, I used the following versions. All work well otherwise, but the visualization (bar) doesn't work. When I save the same file locally and load it, the visualization works, so I know the data is proper.
```
	 "data": "http://cors.io/?u=https://docs.google.com/spreadsheets/d/1EB5P5mMrlmdHNcvbT0nQMXOz9P2vj-kxn4BL24eO6Qc/pub?output=csv",
	 "data": "https://docs.google.com/spreadsheets/d/1EB5P5mMrlmdHNcvbT0nQMXOz9P2vj-kxn4BL24eO6Qc/pub?output=csv",
	 "data": "https://docs.google.com/spreadsheets/d/1EB5P5mMrlmdHNcvbT0nQMXOz9P2vj-kxn4BL24eO6Qc/export?format=csv&id=1EB5P5mMrlmdHNcvbT0nQMXOz9P2vj-kxn4BL24eO6Qc",
	 "data": "http://cors.io/?u=https://docs.google.com/spreadsheets/d/1EB5P5mMrlmdHNcvbT0nQMXOz9P2vj-kxn4BL24eO6Qc/export?format=csv&id=1EB5P5mMrlmdHNcvbT0nQMXOz9P2vj-kxn4BL24eO6Qc",
```

**Comment by answerquest** [comment]
Alternatively, can we pass a variable holding CSV or JSON data instead of specifying a csv file? Then I can do a workaround.. using Papa.parse or similar

**Comment by UtkarshPable** [comment]
Hi answerquest,

Currently we are not supporting direct fetching of data from spreadsheets. However, as your spreadsheet is dynamically getting updated, you can write a script to store the updated data in a variable as a JSON data. This will allow you to directly pass this variable as data.

For example:
```
var k = new PykCharts.multiD.bar({
data: spreadsheet_data // spreadsheet_data is the variable holding JSON data
})
```
Let us know, if this workaround solves your problem.
