### ISSUE TITLE
Error: Can't find variable: d3

### ISSUE THREAD

**Issue by roshanhadal** [pykih/PykCharts.js#26]
I keep getting this error on slow network speeds. Pykih scripts are the first to be downloaded and referenced last in my scripts. I am not sure why it is not able to initialize. I just tried adding the d3 script directly `<script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>` and it seems to solve the problem. Is it a d3 issue that is resolved in the latest release? Let me know how to get around this problem. Attaching screenshots with console errors.
<img width="1438" alt="screen shot 2016-04-15 at 2 07 33 pm" src="https://cloud.githubusercontent.com/assets/8522615/14565004/a6c87d14-0346-11e6-8582-6cbd3f272d81.png">
<img width="1430" alt="screen shot 2016-04-15 at 2 06 45 pm" src="https://cloud.githubusercontent.com/assets/8522615/14565005/a6c9b850-0346-11e6-9702-a60add0fe510.png">

**Comment by nehalgala** [comment]
Hey Roshan,

Write all the pykcharts related code inside window.PykChartsInit:

`window.PykChartsInit = function (e) {
      // Write your pykcharts code here.
});`

This should solve your problem.

**Comment by roshanhadal** [comment]
I am using PkyCharts deep inside my AngularJS controller which doesn't allow me to initialize in this fashion. Also, I am executing the chart inside my logic for the page. Is it ok if I do a dummy load in my index.html like below? Let me know if there are other ways to init pykcharts inside frameworks like Angular JS.

 ```
<script>
        window.PykChartsInit = function (e) {
          console.log("PykCharts dummy load");
        }
  </script>
```

**Comment by roshanhadal** [comment]
Is there any other way to init pykcharts inside other JavaScript lib?

**Comment by roshanhadal** [comment]
Is Pkycharts hosted on any CDN?

**Comment by nehalgala** [comment]
hey,

**Comment by nehalgala** [comment]
Since AngularJS controller doesn't allow you to initialize in the format required by pykcharts you can include all the dependency files in index.html.

No, Pykcharts is currently not hosted on any CDN.

**Comment by roshanhadal** [comment]
Thanks! Loading all the pykih-charts/assets/lib/*.js in index.html seems to be working. I didn't realize the dependencies inside of assets/lib. I will keep a watch for some more days and confirm again.

**Comment by prometheansacrifice** [comment]
@nehalgala It looks like this issue can be closed.
